export const scheduleData = [
    {
        id:  1,
        group: "SP-2-22",
        monday: "PE",
        tuesday: "PE",
        wednesday: "PE",
        thursday: "PE",
        friday: "PE",
    },
    {
        id:  2,
        group: "SP-2-22",
        monday: "PE",
        tuesday: "PE",
        wednesday: "PE",
        thursday: "PE",
        friday: "PE",
    },
    {
        id:  3,
        group: "SP-2-22",
        monday: "PE",
        tuesday: "PE",
        wednesday: "PE",
        thursday: "PE",
        friday: "PE",
    },
    {
        id:  4,
        group: "SP-2-22",
        monday: "PE",
        tuesday: "PE",
        wednesday: "PE",
        thursday: "PE",
        friday: "PE",
    },
    {
        id:  5,
        group: "SP-2-22",
        monday: "PE",
        tuesday: "PE",
        wednesday: "PE",
        thursday: "PE",
        friday: "PE",
    },
]