export const scheduleData = [
    {
        id: 1,
        group: "SP-2-22",
        monday: "Math",
        tuesday: "Physics",
        wednesday: "Chemistry",
        thursday: "Biology",
        friday: "Computer Science",
    },
    {
        id: 2,
        group: "SP-2-22",
        monday: "History",
        tuesday: "Literature",
        wednesday: "Geography",
        thursday: "Economics",
        friday: "Art",
    },
    {
        id: 3,
        group: "SP-2-22",
        monday: "Foreign Language",
        tuesday: "Music",
        wednesday: "Philosophy",
        thursday: "Psychology",
        friday: "Sociology",
    },
    {
        id: 4,
        group: "SP-2-22",
        monday: "Algebra",
        tuesday: "Geometry",
        wednesday: "Calculus",
        thursday: "Statistics",
        friday: "Trigonometry",
    },
    {
        id: 5,
        group: "SP-2-22",
        monday: "Physical Education",
        tuesday: "Health",
        wednesday: "Drama",
        thursday: "Debate",
        friday: "Robotics",
    },
]